  
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install packege and requrements
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements-dev.txt
    # Runs a set of commands using the runners shell.
    - name: Run the tests and check for test coverage.
      run: pytest
        
    - name: Enforce code style ('relaxed' line length limit is set in .flake8 config file).
      run: flake8
        
    - name: Build the documentation.
      run: make -C docs html

    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
    # ===============================
